services:
  epapers:
    container_name: epapers
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file:
      - .env
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USERNAME: ${MYSQL_USERNAME}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}