services:
  mariadb:
    image: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  epapers:
    container_name: epapers
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USERNAME: ${MYSQL_USERNAME}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - mariadb